#!/usr/bin/env bash
# standards/install-hooks.sh
#
# Installs the standards version enforcement pre-commit hook.
# For use in the claude-templates repo only (not consumer projects).
#
# Installs:
#   Git hook → .git/hooks/pre-commit  (copied — git hooks are not committed)
#
# If a versioning pre-commit hook already exists, creates a composite wrapper
# that runs both hooks via pre-commit.d/. Idempotent — safe to run multiple times.
#
# Usage:
#   ~/Projects/Claude\ Templates/standards/hooks/standards/install-hooks.sh

set -euo pipefail

# --- Helpers ---
red()   { printf '\033[1;31m%s\033[0m\n' "$*"; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
dim()   { printf '\033[2m%s\033[0m\n' "$*"; }

# --- Resolve paths ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Verify git repo (supports worktrees) ---
GIT_DIR="$(git rev-parse --git-dir 2>/dev/null)" || {
  red "ERROR: Not inside a git repository."
  red "Run this script from your project's root directory."
  exit 1
}

HOOKS_DIR="${GIT_DIR}/hooks"
TARGET="${HOOKS_DIR}/pre-commit"
SOURCE="${SCRIPT_DIR}/pre-commit-version-check.sh"
PRECOMMIT_D="${HOOKS_DIR}/pre-commit.d"

# --- Install git pre-commit hook ---
mkdir -p "$HOOKS_DIR"

# Case 1: Composite pre-commit.d/ already exists — just update our hook
if [ -d "$PRECOMMIT_D" ]; then
  cp "$SOURCE" "${PRECOMMIT_D}/02-standards-version.sh"
  chmod +x "${PRECOMMIT_D}/02-standards-version.sh"
  green "✓  standards pre-commit hook → ${PRECOMMIT_D}/02-standards-version.sh (updated)"
  dim "   Both versioning and standards hooks will run on commit."
  exit 0
fi

# Case 2: Existing hook is the versioning hook — set up composite wrapper
if [ -f "$TARGET" ] && [ ! -L "$TARGET" ] && grep -qF "V.MM.PPPP" "$TARGET" 2>/dev/null; then
  dim "Existing pre-commit hook is the versioning hook."
  dim "Creating a composite wrapper that runs both hooks."

  # Back up existing hook
  cp "$TARGET" "${TARGET}.versioning.bak"

  # Create wrapper that runs all hooks in pre-commit.d/
  cat > "$TARGET" << 'WRAPPER'
#!/usr/bin/env bash
# Composite pre-commit hook — runs all registered hooks.
# Auto-generated by standards/install-hooks.sh

HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for hook in "$HOOK_DIR"/pre-commit.d/*; do
  [ -x "$hook" ] || continue
  "$hook" || exit $?
done
WRAPPER
  chmod +x "$TARGET"

  # Move hooks into pre-commit.d/
  mkdir -p "$PRECOMMIT_D"
  cp "${TARGET}.versioning.bak" "${PRECOMMIT_D}/01-versioning.sh"
  chmod +x "${PRECOMMIT_D}/01-versioning.sh"
  cp "$SOURCE" "${PRECOMMIT_D}/02-standards-version.sh"
  chmod +x "${PRECOMMIT_D}/02-standards-version.sh"
  rm -f "${TARGET}.versioning.bak"

  green "✓  standards pre-commit hook → ${PRECOMMIT_D}/02-standards-version.sh"
  dim "   Both versioning and standards hooks will run on commit."
  exit 0
fi

# Case 3: No existing hook or different hook — back up and install
if [ -f "$TARGET" ] && [ ! -L "$TARGET" ]; then
  dim "Backing up existing pre-commit → pre-commit.bak"
  cp "$TARGET" "${TARGET}.bak"
fi

cp "$SOURCE" "$TARGET"
chmod +x "$TARGET"
green "✓  standards pre-commit hook → ${TARGET}"
dim "   Enforces: version bump required when standards/*.md content changes"
